require 'default-config'
require 'keymappings'
require 'settings'
require 'theme'
require 'plugins'
require 'utils'
require 'lv-galaxyline'
require 'lv-treesitter'
require 'lv-telescope.mappings'
require 'lsp'
-- require 'lsp.emmet-ls'
vim.g.colors_name = O.colorscheme
